[workspace]
resolver = "2"
members = [
    "crates/nano-installer-core",
    "crates/nano-installer-cli",
    "crates/nano-installer-gui",
    "crates/nano-installer-stub-lzma",
    "crates/nano-installer-stub-zlib",
    "crates/nano-installer-uninstaller",
]

[workspace.package]
version = "2026.9.16"
edition = "2021"
rust-version = "1.88"
authors = ["nano-installer contributors"]
description = "Native configuration-driven Windows installer framework"
license = "MIT"
repository = "https://github.com/Nick2781/nano-installer"

[workspace.dependencies]
anyhow = "1.0"
roxmltree = "0.20"
serde_json = "1.0"
tempfile = "3.8"
winres = "0.1"
image = { version = "0.25.8", default-features = false, features = ["png"] }
sevenz-rust = { version = "0.6.1", default-features = false }
zip = { version = "0.6.6", default-features = false, features = ["deflate"] }
rhai = { version = "1.24", default-features = false, features = ["std", "only_i64", "no_module", "no_custom_syntax"] }
eframe = { version = "0.33.0", default-features = false, features = ["default_fonts", "glow"] }
rfd = { version = "0.14.1", default-features = false }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
panic = "abort"
