[package]
name = "nano-installer-zlib"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "ZIP/Deflate runtime stub for nano-installer"

[[bin]]
name = "zlib-x64"
path = "src/x64.rs"

[dependencies]
nano-installer-lib = { path = "../../lib", default-features = false, features = ["payload-zip"] }
anyhow.workspace = true
tracing.workspace = true
