[package]
name = "nano-installer-lib"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "Shared library for nano-installer"

[lib]
name = "nano_installer"
path = "src/lib.rs"

[dependencies]
# 从 workspace 继承
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
once_cell.workspace = true

# 日志库
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true

# GUI 库
eframe.workspace = true
egui.workspace = true
image.workspace = true

# 工具库
uuid.workspace = true
chrono.workspace = true
parking_lot.workspace = true
walkdir.workspace = true
raw-window-handle.workspace = true
tempfile.workspace = true

# 校验库
crc32fast.workspace = true
sha2 = { workspace = true, optional = true }

# XML 解析库
roxmltree.workspace = true

# 正则表达式库
regex = { workspace = true, optional = true }

# 脚本引擎
rhai.workspace = true

# 布局引擎
taffy.workspace = true

# 压缩库
flate2.workspace = true
zip = { workspace = true, optional = true }
lzma-rs.workspace = true

# Windows specific
[target.'cfg(windows)'.dependencies]
windows.workspace = true
winreg.workspace = true

[features]
default = ["payload-lzma", "payload-zip"]
payload-lzma = ["dep:regex", "dep:sha2"]
payload-zip = ["dep:zip"]

