[package]
name = "nano-installer-native-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "Native nano-installer project builder"

[[bin]]
name = "nano-installer-native-x64"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
nano-installer-core = { path = "../nano-installer-core" }

[build-dependencies]
winres.workspace = true
image.workspace = true
