[package]
name = "uninst"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "Uninstaller stub - same engine as installer, runs in uninstall mode"

[[bin]]
name = "uninst-x64"
path = "src/x64.rs"

[dependencies]
nano-installer-lib = { path = "../../lib", default-features = false }
anyhow.workspace = true
tracing.workspace = true
