[package]
name = "nano-installer-stub-lzma"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "Native x64 7z/LZMA installer runtime stub"

[[bin]]
name = "lzma-stub-native"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
nano-installer-core = { path = "../nano-installer-core" }
sevenz-rust.workspace = true
