use crate::common::error::Error;
use regex::Regex;
use std::path::Path;
use tracing::{info, warn};

/// 渠道标识管理器
pub struct ChannelManager {
    product_name: String,
    install_path: String,
    channel_regex: Option<Regex>,
    default_channel: String,
}

impl ChannelManager {
    pub fn new(
        product_name: String,
        install_path: String,
        channel_regex: Option<String>,
        default_channel: String,
    ) -> Result<Self, Error> {
        let compiled_regex =
            if let Some(regex_str) = channel_regex {
                Some(Regex::new(&regex_str).map_err(|e| {
                    Error::InstallationFailed(format!("Invalid channel regex: {}", e))
                })?)
            } else {
                None
            };

        Ok(Self {
            product_name,
            install_path,
            channel_regex: compiled_regex,
            default_channel,
        })
    }

    /// 从文件名提取渠道信息
    pub fn extract_channel_from_filename(&self, filename: &str) -> String {
        if let Some(ref regex) = self.channel_regex {
            if let Some(captures) = regex.captures(filename) {
                if let Some(channel) = captures.get(1) {
                    let extracted = channel.as_str().to_string();
                    info!(
                        "Extracted channel from filename '{}': {}",
                        filename, extracted
                    );
                    return extracted;
                }
            }
        }

        // 默认渠道提取逻辑
        if let Some(channel) = self.extract_channel_default(filename) {
            info!(
                "Extracted channel using default logic from '{}': {}",
                filename, channel
            );
            return channel;
        }

        warn!(
            "Could not extract channel from filename '{}', using default: {}",
            filename, self.default_channel
        );
        self.default_channel.clone()
    }

    /// 默认渠道提取逻辑
    fn extract_channel_default(&self, filename: &str) -> Option<String> {
        // 尝试从文件名中提取渠道信息
        // 例如: TapTap_Setup_CN.exe -> CN
        //       TapTap_Setup_Global.exe -> Global

        if let Some(underscore_pos) = filename.rfind('_') {
            if let Some(dot_pos) = filename.rfind('.') {
                if underscore_pos < dot_pos {
                    let potential_channel = &filename[underscore_pos + 1..dot_pos];
                    if !potential_channel.is_empty()
                        && potential_channel.chars().all(|c| c.is_alphanumeric())
                    {
                        return Some(potential_channel.to_string());
                    }
                }
            }
        }

        None
    }

    /// 写入渠道配置文件
    pub fn write_channel_config(&self, channel: &str) -> Result<(), Error> {
        let config_path = Path::new(&self.install_path).join("channel.conf");

        let config_content = format!(
            "# Channel configuration for {}\n\
             # Generated by nano-installer\n\
             channel={}\n\
             timestamp={}\n",
            self.product_name,
            channel,
            chrono::Utc::now().timestamp()
        );

        std::fs::write(&config_path, config_content).map_err(|e| {
            Error::InstallationFailed(format!("Failed to write channel config: {}", e))
        })?;

        info!("Written channel config to {:?}: {}", config_path, channel);
        Ok(())
    }

    /// 读取渠道配置
    pub fn read_channel_config(&self) -> Result<Option<String>, Error> {
        let config_path = Path::new(&self.install_path).join("channel.conf");

        if !config_path.exists() {
            return Ok(None);
        }

        let content = std::fs::read_to_string(&config_path).map_err(|e| {
            Error::InstallationFailed(format!("Failed to read channel config: {}", e))
        })?;

        // 解析配置文件
        for line in content.lines() {
            if line.starts_with("channel=") {
                let channel = line.strip_prefix("channel=").unwrap_or("").trim();
                if !channel.is_empty() {
                    info!("Read channel from config: {}", channel);
                    return Ok(Some(channel.to_string()));
                }
            }
        }

        Ok(None)
    }

    /// 删除渠道配置文件
    pub fn remove_channel_config(&self) -> Result<(), Error> {
        let config_path = Path::new(&self.install_path).join("channel.conf");

        if config_path.exists() {
            std::fs::remove_file(&config_path).map_err(|e| {
                Error::UninstallationFailed(format!("Failed to remove channel config: {}", e))
            })?;
            info!("Removed channel config: {:?}", config_path);
        }

        Ok(())
    }

    /// 获取当前渠道
    pub fn get_current_channel(&self) -> String {
        match self.read_channel_config() {
            Ok(Some(channel)) => channel,
            _ => self.default_channel.clone(),
        }
    }

    /// 验证渠道名称
    pub fn validate_channel(&self, channel: &str) -> bool {
        // 渠道名称应该只包含字母、数字、下划线和连字符
        channel
            .chars()
            .all(|c| c.is_alphanumeric() || c == '_' || c == '-')
    }
}
